package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"go-learn/graphql2/auth"
	"go-learn/graphql2/graph/model"
	"sort"
	"time"
)

// Добавление нового видео
func (r *mutationResolver) CreateVideo(ctx context.Context, input model.NewVideo) (*model.Video, error) {
	// Аутентификация
	if user := auth.ForContext(ctx); user == nil || !user.IsAdmin {
		return &model.Video{}, fmt.Errorf("Доступ запрещен")
	}

	// Данные видео
	var video model.Video
	video.Name = input.Name
	video.UserID = input.UserID
	video.Description = input.Description
	video.URL = input.URL
	video.CreatedAt = model.Timestamp(time.Now())
	video.Genre = input.Genre

	// ID и хранилище
	id := input.ID
	n := len(r.Resolver.videos)
	if r.Resolver.videos == nil {
		r.Resolver.videos = make(map[model.Num]model.Video)
	}

	if id == nil { // Создание нового видео

		newId := model.Num(n + 1)
		video.ID = newId
		r.Resolver.videos[newId] = video

	} else { // Редактирование видео

		videoId := model.Num(*id)
		_, ok := r.Resolver.videos[videoId]
		if !ok {
			return nil, fmt.Errorf("видео не найдено")
		}
		video.ID = videoId
		r.Resolver.videos[videoId] = video
	}

	// Оповещение подписчиков
	for _, observer := range videoPublishedSubs {
		observer <- &video
	}

	return &video, nil
}

// Получение видео
func (r *queryResolver) Video(ctx context.Context, id model.Num) (*model.Video, error) {
	video, ok := r.Resolver.videos[id]
	if !ok {
		return nil, fmt.Errorf("видео не найдено")
	}
	return &video, nil
}

// Получение списка видео
func (r *queryResolver) Videos(ctx context.Context, genre *model.Genre, limit *int, offset *int) ([]*model.Video, error) {
	n := len(r.Resolver.videos)
	videos := make([]*model.Video, 0, n)

	// Обход видео и запись их в срез
	for _, video := range r.Resolver.videos {
		video := video

		// Фильтрация по жанру
		if genre != nil && (video.Genre == nil || *genre != *video.Genre) {
			continue
		}
		videos = append(videos, &video)
	}

	// Сортировка среза видео по ID
	sort.Slice(videos, func(i, j int) bool {
		return videos[i].ID < videos[j].ID
	})

	// Лимит и смещение
	from, to := 0, n
	if *offset >= 0 && *offset < n {
		from = *offset
	}
	if *offset+*limit >= 0 && n > *offset+*limit {
		to = *offset + *limit
	}

	return videos[from:to], nil
}

// Подписка на публикацию видео
func (r *subscriptionResolver) VideoPublished(ctx context.Context) (<-chan *model.Video, error) {
	// Подписчики и ID
	n := len(videoPublishedSubs)
	id := n + 1

	// Создание нового подписчика
	videoCh := make(chan *model.Video, 1)
	go func() {
		<-ctx.Done()
	}()
	videoPublishedSubs[id] = videoCh

	return videoCh, nil
}

// Получение пользователя
func (r *videoResolver) User(ctx context.Context, obj *model.Video) (*model.User, error) {
	if obj.UserID == 1 {
		return &model.User{
			ID:    1,
			Name:  "Greg Frost",
			Email: "greg-frost@yandex.ru",
		}, nil
	}
	return &model.User{ID: obj.UserID}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Video returns VideoResolver implementation.
func (r *Resolver) Video() VideoResolver { return &videoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type videoResolver struct{ *Resolver }
