package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"golearn/graphql2/graph/model"
	"sort"
	"time"
)

// CreateVideo is the resolver for the createVideo field.
func (r *mutationResolver) CreateVideo(ctx context.Context, input model.NewVideo) (*model.Video, error) {
	id := input.ID
	n := len(r.Resolver.videos)
	if n == 0 {
		r.Resolver.videos = make(map[model.Num]model.Video)
	}

	var video model.Video
	video.Name = input.Name
	video.UserID = input.UserID
	video.Description = input.Description
	video.URL = input.URL
	video.CreatedAt = model.Timestamp(time.Now())
	video.Genre = input.Genre

	if id == nil {
		newId := model.Num(n + 1)
		video.ID = newId
		r.Resolver.videos[newId] = video
	} else {
		videoId := model.Num(*id)
		_, ok := r.Resolver.videos[videoId]
		if !ok {
			return nil, fmt.Errorf("видео не найдено")
		}
		video.ID = videoId
		r.Resolver.videos[videoId] = video
	}

	return &video, nil
}

// Video is the resolver for the video field.
func (r *queryResolver) Video(ctx context.Context, id model.Num) (*model.Video, error) {
	video, ok := r.Resolver.videos[id]
	if !ok {
		return nil, fmt.Errorf("видео не найдено")
	}
	return &video, nil
}

// Videos is the resolver for the videos field.
func (r *queryResolver) Videos(ctx context.Context, genre *model.Genre, limit *int, offset *int) ([]*model.Video, error) {
	n := len(r.Resolver.videos)
	videos := make([]*model.Video, 0, n)
	for _, video := range r.Resolver.videos {
		video := video
		if genre != nil && (video.Genre == nil || *genre != *video.Genre) {
			continue
		}
		videos = append(videos, &video)
	}

	sort.Slice(videos, func(i, j int) bool {
		return videos[i].ID < videos[j].ID
	})

	from, to := 0, n
	if *offset >= 0 && *offset < n {
		from = *offset
	}
	if *offset+*limit >= 0 && n > *offset+*limit {
		to = *offset + *limit
	}

	return videos[from:to], nil
}

// Tick is the resolver for the tick field.
func (r *subscriptionResolver) Tick(ctx context.Context) (<-chan *model.Time, error) {
	ch := make(chan *model.Time)

	go func() {
		defer close(ch)

		for {
			time.Sleep(time.Second)

			currentTime := time.Now()
			t := &model.Time{
				UnixTime:  int(currentTime.Unix()),
				TimeStamp: currentTime.Format(time.RFC3339),
			}

			select {
			case <-ctx.Done():
				return
			case ch <- t:
			}
		}
	}()

	return ch, nil
}

// VideoPublished is the resolver for the videoPublished field.
func (r *subscriptionResolver) VideoPublished(ctx context.Context) (<-chan *model.Video, error) {
	panic(fmt.Errorf("not implemented: VideoPublished - videoPublished"))
}

// User is the resolver for the user field.
func (r *videoResolver) User(ctx context.Context, obj *model.Video) (*model.User, error) {
	if obj.UserID == 1 {
		return &model.User{
			ID:    1,
			Name:  "Greg Frost",
			Email: "greg-frost@yandex.ru",
		}, nil
	}
	return &model.User{ID: obj.UserID}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Video returns VideoResolver implementation.
func (r *Resolver) Video() VideoResolver { return &videoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type videoResolver struct{ *Resolver }
